#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Nov 25, 2017 02:25:34 PM

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1


import wpm_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = Result (root)
    wpm_support.init(root, top)
    root.mainloop()

w = None
def create_Result(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = Result (w)
    wpm_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Result():
    global w
    w.destroy()
    w = None


class Result:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {URW Gothic L} -size 12 -weight normal "  \
            "-slant roman -underline 0 -overstrike 0"

        top.geometry("320x199+510+316")
        top.title("Result")
        top.configure(background="#4CBBC6")
        top.configure(highlightcolor="black")



        self.wpmMessage = Message(top)
        self.wpmMessage.place(relx=0.06, rely=0.1, relheight=0.75, relwidth=0.85)

        self.wpmMessage.configure(background="#4CBBC6")
        self.wpmMessage.configure(font=font10)
        self.wpmMessage.configure(justify=CENTER)
        self.wpmMessage.configure(text='''Message''')
        self.wpmMessage.configure(width=273)






if __name__ == '__main__':
    vp_start_gui()



