#! /usr/bin/env python
#
# Support module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Nov 25, 2017 02:25:26 PM


try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1


def init(top, gui, *args, **kwargs):
    global w, top_level, root, masterroot
    w = gui
    top_level = top
    root = top
    masterroot = args[0]
    root.resizable(width=False, height=False)

    if args[1] < 10:
        message = str(args[1]) + " WPM\n\n Newbie typist"

    elif args[1] < 25:
        message = str(args[1]) + " WPM\n\n Still using two fingers ?"

    elif args[1] < 40:
        message = str(args[1]) + " WPM\n\n FaceBook User"

    elif args[1] < 50:
        message = str(args[1]) + " WPM\n\n You are among the world average"

    elif args[1] < 60:
        message = str(args[1]) + " WPM\n\n You know your keyboard"

    elif args[1] < 80:
        message = str(args[1]) + " WPM\n\n Touch Typist"

    elif args[1] < 110:
        message = str(args[1]) + " WPM\n\n Professional"
        
    else:
        message = str(args[1]) + " WPM\n\n Dude, stop get a life"
    


    w.wpmMessage.configure(text=message)
    root.wait_visibility()
    root.transient(masterroot)
    root.focus_force()
    root.grab_set()

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import WPM.wpm
    WPM.wpm.vp_start_gui()
