#! /usr/bin/env python
#
# Support module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Nov 27, 2017 01:31:37 AM

'''
   * Don't even try to understand this.
   * I wrote it, and I have no idea why it works.
   * But it does. My subconscious is that good.
'''

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1



def init(top, gui, *args, **kwargs):
    global w, top_level, root, masterroot
    w = gui
    top_level = top
    root = top
    masterroot = args[0]
    root.resizable(width=False, height=False)


    message = "Type Master " + u'\u00A9' + "2017 \n" \
         "Application to improve typing speed and its habits\n" \
         "Author: Nihal Murmu.\n" \
         "email: nhlmrm@gmail.com\n\n" \
         "Software used: Page\n" \
         "Author: Don Rozenberg\n" \
         "email: Don.Rozenberg@gmail.com\n\n" \
         "words from americanliterature.com\n\n" \
         "Application Icon made by Prosymbols from www.flaticon.com"


    w.AboutMessage.configure(text=message)
    root.wait_visibility()
    root.transient(masterroot)
    root.focus_force()
    root.grab_set()

    

def destroy_window():
    # Function which closes the window.
    global top_level

    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import About.about
    About.about.vp_start_gui()


