#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Nov 27, 2017 01:31:42 AM


try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1


import about_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = About (root)
    about_support.init(root, top)
    root.mainloop()

w = None
def create_About(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = About (w)
    about_support.init(w, top, *args, **kwargs)

    return (w, top)

def destroy_Credits():
    global w
    w.destroy()
    w = None


class About:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {URW Gothic L} -size 10 -weight normal "  \
            "-slant roman -underline 0 -overstrike 0"

        top.geometry("330x280+537+289")
        top.configure(background="#4CBBC6")
        top.title("About")


        self.AboutMessage = Message(top)
        self.AboutMessage.place(relx=0.06, rely=0.05, relheight=0.90
                , relwidth=0.85)
        self.AboutMessage.configure(font=font10)
        self.AboutMessage.configure(text='''Message''')
        self.AboutMessage.configure(width=273)
        self.AboutMessage.configure(background="#4CBBC6")


if __name__ == '__main__':
    vp_start_gui()

